# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        PLONE_VERSION: [4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Set up Env
        run: |
          pip install -r requirements.txt coverage==5.3.1 wheel
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.PLONE_VERSION }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.PLONE_VERSION }}
      - name: Buildout
        run: |
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: Code analysis
        run: |
          bin/code-analysis
      - name: Test coverage
        run: |
          bin/coverage run bin/test
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
